# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 03:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_activeYesNo', models.BooleanField(default=False)),
                ('full_address', models.CharField(blank=True, max_length=200, null=True)),
                ('accountType', models.CharField(blank=True, max_length=100, null=True)),
                ('isProfileComplete', models.BooleanField(default=False)),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
