# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_is', models.TextField(blank=True, null=True)),
                ('notification_date_time', models.DateTimeField(auto_now_add=True)),
                ('notification_read_yes_no', models.BooleanField(default=False)),
                ('notification_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.MyUser')),
            ],
        ),
    ]
