# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_notificationmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyId', models.CharField(blank=True, max_length=15, null=True)),
                ('operationFormID', models.BigIntegerField(blank=True, null=True)),
                ('voyageId', models.BigIntegerField(blank=True, null=True)),
                ('BLdate', models.DateField(blank=True, null=True)),
                ('vesselId', models.BigIntegerField(blank=True, null=True)),
                ('VesselName', models.CharField(blank=True, max_length=350, null=True)),
                ('buyerId', models.BigIntegerField(blank=True, null=True)),
                ('buyerName', models.CharField(blank=True, max_length=350, null=True)),
                ('sellerId', models.BigIntegerField(blank=True, null=True)),
                ('sellerName', models.CharField(blank=True, max_length=350, null=True)),
                ('producerId', models.BigIntegerField(blank=True, null=True)),
                ('producerName', models.CharField(blank=True, max_length=350, null=True)),
                ('loadPortId', models.BigIntegerField(blank=True, null=True)),
                ('loadPortDefinition', models.CharField(blank=True, max_length=350, null=True)),
                ('loadCountryCode', models.BigIntegerField(blank=True, null=True)),
                ('loadCountry', models.CharField(blank=True, max_length=350, null=True)),
                ('dischargePortId', models.BigIntegerField(blank=True, null=True)),
                ('dischargePortDefinition', models.CharField(blank=True, max_length=350, null=True)),
                ('dischargeCountryCode', models.BigIntegerField(blank=True, null=True)),
                ('dischargeCountry', models.CharField(blank=True, max_length=150, null=True)),
                ('productId', models.CharField(blank=True, max_length=60, null=True)),
                ('productDefinition', models.CharField(blank=True, max_length=400, null=True)),
                ('operationLine', models.CharField(blank=True, max_length=20, null=True)),
                ('packingType', models.CharField(blank=True, max_length=25, null=True)),
                ('packingTypeDefinition', models.CharField(blank=True, max_length=250, null=True)),
                ('totalQuantity', models.CharField(blank=True, max_length=150, null=True)),
                ('ETALoadPort', models.CharField(blank=True, max_length=200, null=True)),
                ('lay', models.DateField(blank=True, null=True)),
                ('can', models.DateField(blank=True, null=True)),
                ('purchaseIncoterm', models.CharField(blank=True, max_length=15, null=True)),
                ('purchaseIncotermDefinition', models.CharField(blank=True, max_length=150, null=True)),
                ('salesIncoterm', models.CharField(blank=True, max_length=15, null=True)),
                ('salesIncotermDefinition', models.CharField(blank=True, max_length=150, null=True)),
                ('shipResp', models.BigIntegerField(blank=True, null=True)),
                ('shipRespDesc', models.CharField(blank=True, max_length=150, null=True)),
                ('tradeOperationsResponsible', models.BigIntegerField(blank=True, null=True)),
                ('tradeOperationsResponsibleDefinition', models.CharField(blank=True, max_length=150, null=True)),
                ('addUser', models.CharField(blank=True, max_length=30, null=True)),
                ('addDate', models.DateField(blank=True, null=True)),
                ('purchaseContractNo', models.BigIntegerField(blank=True, null=True)),
                ('purchaseContractLine', models.IntegerField(blank=True, null=True)),
                ('salesContractNo', models.BigIntegerField(blank=True, null=True)),
                ('salesContractLine', models.IntegerField(blank=True, null=True)),
                ('approvalId', models.CharField(blank=True, max_length=40, null=True)),
                ('approvalSubjectStatus', models.CharField(blank=True, max_length=150, null=True)),
                ('freightPMT', models.CharField(blank=True, max_length=50, null=True)),
                ('freightCurrency', models.CharField(blank=True, max_length=100, null=True)),
                ('loadingRate', models.BigIntegerField(blank=True, null=True)),
                ('dischargeRate', models.BigIntegerField(blank=True, null=True)),
                ('netBLQuantity', models.FloatField(blank=True, null=True)),
                ('purchasePrice', models.FloatField(blank=True, null=True)),
                ('salesPrice', models.FloatField(blank=True, null=True)),
                ('netCommision', models.CharField(blank=True, max_length=150, null=True)),
                ('sample', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
