# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_datamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='BLdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='addDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='can',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='lay',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
